# circleCI build file
version: 2.1
jobs:
  build:
    docker:
      - image: yakworks/alpine-java:jdk8-builder

    environment:
      #MALLOC_ARENA_MAX: 2
      #GRADLE_OPTS: "-Xmx3048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dorg.gradle.daemon=false" #daemon false doesn't seem to get picked up by fork
      TERM: dumb

    parallelism: 1
    # resource_class: large

    steps:
      - checkout
      # Download and cache dependencies
      - run:
          name: cat build.gradle files for cache key
          command: cat gradle.properties build.gradle plugin/build.gradle examples/app/build.gradle examples/rest-security/build.gradle > cache-checksum.tmp
      - restore_cache:
          keys:
            - gradle-{{ checksum "cache-checksum.tmp" }}

      # see https://github.com/palantir/gradle-configuration-resolver-plugin
      # this also kind of helps with the memory issue we keep running into by breaking it up
      - run:
          name: ✔︎ -- Downloads Dependencies [gradle resolveConfigurations]
          command: gradle resolveConfigurations --no-daemon

      # compiling as a seperate step before running check helps with the "finished with non-zero exit value 137" error
      - run:
          name: ✔︎ -- Compile [gradle classes]
          command: gradle classes --no-daemon

      - save_cache:
          paths: ["~/.m2", "~/.gradle"]
          key: gradle-{{ checksum "cache-checksum.tmp" }}

      - run:
          name: ✔︎ -- Checks Linter and Tests [gradle check]
          command: gradle check --no-daemon

      - store_artifacts:
          path: plugin/build/reports/tests/test/
          destination: test-reports/unit/
      - store_artifacts:
          path: plugin/build/reports/codenarc/
          destination: codenarc/
      - store_test_results:
          path: plugin/build/test-results
      - store_artifacts:
          path: examples/app/build/reports/tests
          destination: test-reports/integration
      - store_test_results:
          path: examples/app/build/test-results
      - store_artifacts:
          path: examples/rest-security/build/reports/tests
          destination: test-reports/integration
      - store_test_results:
          path: examples/rest-security/build/test-results

      ### Finally do the build and publish. ciPublish will check if this is a PR or on a branch that should not be published
      - compare-url/reconstruct # orb to make the CIRCLE_COMPARE_URL when using workflows
      - run:
          name: ✔︎ -- Publish plugin if needed [gradle ciPublish]
          command: |
            CIRCLE_COMPARE_URL=$(cat CIRCLE_COMPARE_URL.txt)
            ./gradlew ciPublish


orbs:
  compare-url: iynere/compare-url@1.1.0

workflows:
  version: 2
  build-flow:
    jobs:
      - build:
          context: bot-context #context with shared ENV vars

